services:

  navidrome:
    image: deluan/navidrome:${NAVIDROME_VERSION:-latest}
    user: ${HOST_USER_ID:-0}:${HOST_GROUP_ID:-0}
    env_file: environment.d/navidrome.env
    environment:
      ND_BACKUP_PATH: /backups
      ND_PLUGINS_ENABLED: true
      ND_PLUGINS_AUTORELOAD: true
    ports:
      - ${NAVIDROME_PORT:-4533}:4533
    volumes:
      - ${MUSIC_PATH}:/music:ro
      - ${BACKUPS_PATH:-./backups}:/backups
      - ${NAVIDROME_DATA_VOLUME:-navidrome-data}:/data
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

  audiomuse-ai-flask:
    image: ghcr.io/neptunehub/audiomuse-ai:${AUDIOMUSE_AI_IMAGE_VERSION:-latest}
    depends_on: [database]
    environment:
      SERVICE_TYPE: flask
      POSTGRES_HOST: ${DATABASE_HOST:-database}
      POSTGRES_PORT: ${DATABASE_PORT:-5432}
      POSTGRES_DB: ${DATABASE_NAME:-audiomuse}
      POSTGRES_USER: ${DATABASE_USER:-audiomuse}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      TEMP_DIR: /app/temp_audio
    ports:
      - ${AUDIOMUSE_PORT:-8000}:8000
    volumes:
      - ${AUDIOMUSE_FLASK_TEMP_AUDIO_VOLUME:-flask-temp-audio}:/app/temp_audio
      - ${AUDIOMUSE_FLASK_PLUGINS_VOLUME:-flask-plugins}:/app/plugin/installed
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

  audiomuse-ai-worker:
    image: ghcr.io/neptunehub/audiomuse-ai:${AUDIOMUSE_AI_IMAGE_VERSION:-latest}
    depends_on: [database]
    environment:
      SERVICE_TYPE: worker
      POSTGRES_HOST: ${DATABASE_HOST:-database}
      POSTGRES_PORT: ${DATABASE_PORT:-5432}
      POSTGRES_DB: ${DATABASE_NAME:-audiomuse}
      POSTGRES_USER: ${DATABASE_USER:-audiomuse}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      TEMP_DIR: /app/temp_audio
    volumes:
      - ${AUDIOMUSE_WORKER_TEMP_AUDIO_VOLUME:-worker-temp-audio}:/app/temp_audio
      - ${AUDIOMUSE_WORKER_PLUGINS_VOLUME:-worker-plugins}:/app/plugin/installed
      - /etc/localtime:/etc/localtime:ro
    labels:
      com.centurylinklabs.watchtower.scope: ${COMPOSE_PROJECT_NAME}
    restart: unless-stopped

  database:
    image: postgres:${POSTGRESS_IMAGE_VERSION:-18.4}
    env_file: environment.d/postgres.env
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-audiomuse}
      POSTGRES_USER: ${DATABASE_USER:-audiomuse}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ${DATABASE_VOLUME:-postgres-data}:/var/lib/postgresql
      - /etc/localtime:/etc/localtime:ro
    labels:
      com.centurylinklabs.watchtower.scope: ${COMPOSE_PROJECT_NAME}
    restart: unless-stopped

  watchtower:
    image: nickfedor/watchtower:${WATCHTOWER_VERSION:-latest}
    env_file: environment.d/watchtower.env
    environment:
      WATCHTOWER_SCOPE: ${COMPOSE_PROJECT_NAME}
    volumes:
      - ${DOCKER_SOCKET:-/var/run/docker.sock}:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    labels:
      com.centurylinklabs.watchtower.scope: ${COMPOSE_PROJECT_NAME}
    restart: unless-stopped

volumes:
  navidrome-data: {}
  flask-plugins: {}
  flask-temp-audio: {}
  worker-plugins: {}
  worker-temp-audio: {}
  postgres-data: {}
